// Default content banks. Hosts can add their own from the app —
// these are just the starting set for a new room.

const DEFAULT_QUESTIONS = [
  "Who's most likely to have a secret situationship they haven't told the group about?",
  "Who's most likely to be texting someone right now that they shouldn't be?",
  "Who's most likely to have the messiest camera roll?",
  "Who's most likely to already be thinking about someone in this room... romantically?",
  "Who's most likely to have a wild story from last weekend they haven't shared yet?",
  "Who's most likely to get the most attention walking into a party?",
  "Who's most likely to have a whole playlist for one specific person?",
  "Who's most likely to have snuck out of a date early?",
  "Who's most likely to be the loudest in a relationship argument?",
  "Who's most likely to have kissed someone in this room?",
  "Who's most likely to have a red flag they're pretending is a green flag?",
  "Who's most likely to slide into someone's DMs after two drinks?",
  "Who's most likely to have the spiciest search history?",
  "Who's most likely to fall for someone way too fast?",
  "Who's most likely to be a menace on a first date?",
  "Who's most likely to have a body count they've rounded down?",
  "Who's most likely to get a text back within 30 seconds, no matter who they text?",
  "Who's most likely to have flirted their way out of a speeding ticket?",
  "Who's most likely to have an ex that still slides into their notifications?",
  "Who's most likely to be the reason a group chat gets renamed?",
  "Who's most likely to have a 'type' that's gotten them in trouble before?",
  "Who's most likely to ghost someone and feel zero guilt about it?",
  "Who's most likely to have the most chaotic dating app bio?",
  "Who's most likely to have a situationship that's lasted way too long?",
  "Who's most likely to be someone's celebrity hall pass?",
  "Who's most likely to send the first 'u up?' text of the night?",
  "Who's most likely to have a secret talent in the bedroom nobody's mentioned?",
  "Who's most likely to have cried over someone who didn't deserve it?",
  "Who's most likely to be way more confident after a couple drinks?",
  "Who's most likely to have a spicy DM from someone right now?",
  "Who's most likely to know exactly how to work a room?",
  "Who's most likely to have the best 'how we met' story in this group?",
  "Who's most likely to be talked about the second they leave the room?",
  "Who's most likely to have a playlist titled something embarrassing?",
  "Who's most likely to have a crush on someone in this exact room?",
];

const DEFAULT_DARES = [
  "Give the least-voted person a 30-second shoulder massage.",
  "Let the group ask your phone's autocomplete to finish 3 sentences.",
  "Do your best sexy strut across the room and back.",
  "Send a text the group dictates to anyone in your contacts.",
  "Let the runner-up pick a song — you sing the chorus, full commitment.",
  "Reveal the last thing you searched on your phone (edited for decency).",
  "Do 20 seconds of your best flirty eye contact with the least-voted person.",
  "Let the group scroll your camera roll for 10 seconds.",
  "Give your best pickup line to the person on your left, in character.",
  "Do a slow-motion dramatic wink at everyone in the room, one by one.",
  "Let the least-voted person pick your profile picture for the next hour.",
  "Speak only in a seductive whisper for the next two rounds.",
  "Do your most convincing sultry runway walk down the hallway and back.",
  "Let the group pick your next text's opening line to a crush or ex.",
  "Give a 15-second 'compliment battle' — no repeats, no stopping.",
  "Do your best impression of someone flirting badly.",
  "Let the least-voted person style your hair for the rest of the night.",
  "Answer the next question in an accent of the group's choosing.",
  "Give the group your honest hot take on the last person you dated.",
  "Do a dramatic slow clap and bow every time your name is said for the rest of the game.",
];

module.exports = { DEFAULT_QUESTIONS, DEFAULT_DARES };
