// Content banks. Add, remove, or rewrite anything — plain strings.
// Questions are [question, qualifier]. The qualifier shows under the question.
// Dares are grouped by flavor so every board has variety.

const RAW_QUESTIONS = [
  // dating + situationships
  ["Who's most likely to be in a situationship they refuse to call a situationship?", "Think “we're just vibing” for eight months straight."],
  ["Who's most likely to text their ex at 2am and call it “closure”?", "Counts if the “hey” comes with a fake excuse."],
  ["Who's most likely to catch feelings after one good conversation?", "One deep talk and they're planning the group trip."],
  ["Who's most likely to leave someone on read for three days, then act like nothing happened?", "Opens it instantly, replies Thursday, zero apology."],
  ["Who's most likely to have a “type” that keeps getting them in trouble?", "Same energy, same problems, different name each time."],
  ["Who's most likely to get the ick over something absolutely tiny?", "Chewing, a laugh, a jacket. It doesn't take much."],
  ["Who's most likely to ghost someone and feel zero guilt?", "Vanishes mid-conversation and sleeps just fine."],
  ["Who's most likely to have the most unhinged dating app bio?", "Reads like a hostage note with emojis."],
  ["Who's most likely to fall for a stranger across the room?", "One eye contact and it's over."],
  ["Who's most likely to rebrand a red flag as a “personality quirk”?", "“I'm just passionate” when they mean “I'm jealous.”"],
  ["Who's most likely to have rizz that works on literally everyone?", "Gets numbers without trying. Annoying, honestly."],
  ["Who's most likely to be thinking about someone in this room right now?", "Counts even if they'd never say it out loud."],
  ["Who's most likely to have a crush they're hiding from the group chat?", "Acts normal around them. Is not normal."],
  ["Who's most likely to send the first “u up?” of the night?", "Types it, deletes it, sends it anyway."],
  ["Who's most likely to get back with their ex for the third time?", "Swears this time is different. It's not."],
  ["Who's most likely to keep a situationship going way past its expiration date?", "Everyone else stopped asking about it months ago."],
  ["Who's most likely to be someone's celebrity hall pass?", "The person everyone's partner secretly allows."],
  ["Who's most likely to have the best “how we met” story?", "The one that ends with “and the rest is history.”"],
  ["Who's most likely to cry over someone who did not deserve it?", "Tears for a person who forgot their birthday."],
  ["Who's most likely to make a whole playlist for one specific person?", "Track seven is the one they'd never send."],
  ["Who's most likely to bail on a date ten minutes in because the vibes were off?", "Checks the vibe, checks the exit, picks the exit."],
  ["Who's most likely to flirt their way out of a speeding ticket?", "Smiles, tilts head, drives off with a warning."],
  ["Who's most likely to be a menace on a first date?", "Orders for them, tells the ex story, steals fries."],
  ["Who's most likely to accidentally like a crush's photo from 2019?", "1am scroll, thumb slips, instant panic."],
  ["Who's most likely to still be lurking their ex's finsta?", "Knows the last three posts by heart."],
  ["Who's most likely to say “nothing serious” and then plan the whole future?", "Says casual, then asks to meet the parents."],
  ["Who's most likely to get a number and never text first?", "Gets the digits, waits for you to blink first."],
  ["Who's most likely to slide into the DMs after two drinks?", "Two drinks in, confidence at max."],
  ["Who's most likely to have a hookup story they swore they'd take to the grave?", "The one that starts with “okay, don't tell anyone.”"],
  ["Who's most likely to fake a phone call to escape a bad date?", "Ringtone goes off, nobody's actually calling."],
  ["Who's most likely to have dated two people in the same friend group?", "The group chat has never been the same."],
  ["Who's most likely to plan the wedding before the second date?", "Already picked the venue and the colors."],
  ["Who's most likely to analyze their crush's Spotify for hidden messages?", "Reads every sad song like it's a text."],
  ["Who's most likely to say “I'm over it” while clearly not over it?", "Says it's fine, then posts a song lyric about it."],

  // phone + chronically online
  ["Who's most likely to have a camera roll that could end a career?", "Screenshots, receipts, 400 blurry photos of nothing."],
  ["Who's most likely to have 9,000 unread emails and zero stress?", "That red badge doesn't scare them at all."],
  ["Who's most likely to post a story and check who watched it within 10 seconds?", "Posts, then refreshes the viewer list for ten minutes."],
  ["Who's most likely to have a screen time that would genuinely scare us?", "The number shows up and everyone goes quiet."],
  ["Who's most likely to have a playlist titled something embarrassing?", "“sad girl hours” or worse."],
  ["Who's most likely to have the spiciest search history?", "Nobody should see the last three searches."],
  ["Who's most likely to screenshot a private convo and send it to the group chat?", "Receipts get shared before the ink dries."],
  ["Who's most likely to text back in under 30 seconds, no matter who it is?", "Phone is permanently attached to their hand."],
  ["Who's most likely to type a whole paragraph, delete it, and send “lol”?", "Wrote an essay, sent three letters."],
  ["Who's most likely to be the reason the group chat got renamed?", "Changes the name, acts like it wasn't them."],
  ["Who's most likely to reply “omg sorry just saw this” to a text from last week?", "Opened it last week, replied today."],
  ["Who's most likely to run a burner account just for lurking?", "Zero followers, sees everything."],
  ["Who's most likely to go viral for something embarrassing?", "One clip and the whole city knows."],
  ["Who's most likely to have a close friends story that is pure chaos?", "Content only fifteen people are cleared to see."],
  ["Who's most likely to be chronically online and proud of it?", "Knows the meme before it's a meme."],
  ["Who's most likely to doomscroll until 4am on a work night?", "One more video turns into sunrise."],
  ["Who's most likely to argue with a stranger in the comments?", "Types “actually” at strangers for sport."],
  ["Who's most likely to have a 400-day streak and no memory of why?", "The streak is the only thing that's lasted."],
  ["Who's most likely to take 47 photos just to post one?", "Photo 46 is the one. Probably."],
  ["Who's most likely to send a voice memo longer than four minutes?", "Press play and clear your schedule."],
  ["Who's most likely to start a podcast nobody asked for?", "Episode one is just them agreeing with themselves."],
  ["Who's most likely to have the most unhinged notes app?", "A grocery list next to a breakup draft."],
  ["Who's most likely to save a contact under a name they'd never say out loud?", "Saved as “do not answer” with a skull."],
  ["Who's most likely to cancel plans five minutes before with “my social battery is dead”?", "Texts “so sorry” while already in pajamas."],
  ["Who's most likely to get roasted in the group chat and take it personally?", "Laughs out loud, plots revenge quietly."],
  ["Who's most likely to have a Pinterest board for a life they don't have yet?", "Has the wedding, the house, and the dog pinned."],

  // party + going out
  ["Who's most likely to be the last one at the party?", "Lights come on and they're still mid-story."],
  ["Who's most likely to get way more confident after a couple drinks?", "Goes from shy to karaoke in two drinks."],
  ["Who's most likely to cry at a party for no reason and be fine five minutes later?", "Big feelings, sudden tears, back at the snacks."],
  ["Who's most likely to hear a stranger's whole life story in the bathroom line?", "Leaves the line knowing everything about someone."],
  ["Who's most likely to start the dance floor all by themselves?", "Doesn't wait for anyone. Owns the room."],
  ["Who's most likely to take over the aux and clear the room?", "Plays a nine-minute remix. The room empties."],
  ["Who's most likely to wake up with zero memory of a convo they swear happened?", "Swears it happened. It didn't. Or did it?"],
  ["Who's most likely to become best friends with the bouncer?", "Knows his name, his kids, and his shift."],
  ["Who's most likely to lose their phone, keys, and wallet in one night?", "All three gone by midnight."],
  ["Who's most likely to be talked about the second they leave the room?", "Door closes and the whispers start."],
  ["Who's most likely to give a toast that turns into a TED Talk?", "Starts with “just a few words.” Ends in chapters."],
  ["Who's most likely to say “one more drink” at midnight and still be here at 3?", "Last call at midnight, three more rounds."],
  ["Who's most likely to pull an Irish exit with zero goodbyes?", "Gone without a word. Nobody noticed. Elite."],
  ["Who's most likely to get kicked out of a venue?", "The kind of night that ends with a security escort."],
  ["Who's most likely to turn a casual hang into a full-blown event?", "Invited four people. Now there's a DJ."],
  ["Who's most likely to know every word to every song and still get them wrong?", "Full volume, full confidence, wrong lyrics."],
  ["Who's most likely to start a conga line and abandon it?", "Starts it, loses interest, wanders off."],
  ["Who's most likely to fall asleep at their own party?", "Host duties end at 11pm sharp."],
  ["Who's most likely to order for the whole table and forget they're the one paying?", "Orders everything, then forgets who's covering it."],
  ["Who's most likely to Venmo request someone for $3?", "The request comes with a note: “for the gum.”"],
  ["Who's most likely to bring a plus-one nobody has ever met?", "“Everyone, this is Chris.” Who's Chris?"],
  ["Who's most likely to start a rumor completely by accident?", "Just meant to share. Now it's a headline."],
  ["Who's most likely to overshare with someone they met five minutes ago?", "Five minutes in and they know your biggest fear."],
  ["Who's most likely to run a karaoke night with zero experience?", "Takes the mic, hosts the night, no training."],
  ["Who's most likely to get a little too emotional during a slow song?", "Hand on chest, eyes closed, thinking of an ex."],
  ["Who's most likely to start a dance battle?", "Steps in the circle, steps on a foot."],
  ["Who's most likely to hype everyone up for a shot and then switch to water?", "Leads the chant, holds the water."],
  ["Who's most likely to get asked “where did you go?” and have no good answer?", "Vanished for an hour. Back with a story."],

  // main character energy
  ["Who's most likely to survive on delusion and iced coffee alone?", "Runs on hope and a large cold brew."],
  ["Who's most likely to get lost with GPS on?", "“Recalculating” is their love language."],
  ["Who's most likely to start a cult by accident?", "Starts a group chat, suddenly people follow the rules."],
  ["Who's most likely to win the lottery and be broke in a year?", "Rich for a week. Broke by next summer."],
  ["Who's most likely to move across the country on a whim?", "Booked a one-way ticket. Told no one."],
  ["Who's most likely to say “five minutes away” while still in bed?", "ETA is a lie. Still horizontal."],
  ["Who's most likely to get a tattoo they regret by next week?", "Great idea at 2am. Terrible by Tuesday."],
  ["Who's most likely to change their whole personality for a new crush?", "Suddenly loves hiking. Hates hiking."],
  ["Who's most likely to adopt a pet at 2am?", "Browses shelters, comes home with a cat."],
  ["Who's most likely to quit their job in the most dramatic way possible?", "Reply-all email, mic drop, no backup plan."],
  ["Who's most likely to get famous and be insufferable about it?", "Mentions it in every single sentence."],
  ["Who's most likely to cry during a commercial?", "A dog food ad takes them out."],
  ["Who's most likely to have one very specific hill they will die on?", "Pineapple pizza, tipping, whatever. They'll fight."],
  ["Who's most likely to be late to their own birthday?", "The cake's already cut by the time they arrive."],
  ["Who's most likely to turn a tiny lie into a whole saga?", "One white lie, now there's a backstory."],
  ["Who's most likely to start a business with an unhinged name?", "The name makes you ask “is this legal?”"],
  ["Who's most likely to survive the apocalypse?", "The one you'd actually want in your crew."],
  ["Who's most likely to get caught lying about something dumb?", "Lies about lunch, caught by the receipt."],
  ["Who's most likely to blame Mercury retrograde for everything?", "It's always the planet's fault. Never theirs."],
  ["Who's most likely to ask “do you think they like me?” every ten minutes?", "Asks again after every text. Every. Text."],
  ["Who's most likely to have the most unhinged unpopular opinion?", "Say it out loud and the room argues for an hour."],
  ["Who's most likely to argue with a self-checkout machine?", "“Unexpected item in the bagging area.” Again."],
  ["Who's most likely to become the villain on a reality show?", "Wins the confessional, loses all the friends."],
  ["Who's most likely to cry if we read their texts out loud?", "Their drafts folder is a crime scene."],
  ["Who's most likely to start therapy and come back with new vocabulary to use against us?", "“I'm setting a boundary” before dessert."],
  ["Who's most likely to get weirdly competitive at a board game?", "It's Uno. They're sweating."],
  ["Who's most likely to flip the table during Monopoly?", "Two hotels on Boardwalk and a meltdown."],
  ["Who's most likely to have the best revenge arc?", "Glow-up and a plan, delivered quietly."],
  ["Who's most likely to be delulu and honestly thriving?", "Dreams big, believes harder, somehow it works."],
  ["Who's most likely to touch grass the least?", "Hasn't seen daylight since the last update."],
  ["Who's most likely to wear last night's outfit and call it a vibe?", "Same outfit, new day, zero shame."],
  ["Who's most likely to talk their way into a VIP section?", "Walks in like they're on the list. They're not."],
  ["Who's most likely to get into an argument with a stranger and win?", "The stranger leaves convinced they were wrong."],
  ["Who's most likely to become a millionaire off a terrible idea?", "Pet rock energy. Somehow it sells."],
  ["Who's most likely to see a notification from their ex and spiral?", "One ping and the whole evening is gone."],
  ["Who's most likely to talk to themselves in public and not care?", "Full conversations. Both sides. Good points."],
  ["Who's most likely to make a dramatic exit from a group chat?", "Leaves with a farewell speech nobody asked for."],
];

const DEFAULT_HINT = "Go with your gut. Pick who'd actually do it.";
const DEFAULT_QUESTIONS = RAW_QUESTIONS.map(([q, h]) => ({ q, h }));

const DEFAULT_DARES = {
  show: [
    "Walk the room like it's a runway. Full strut, zero smiling.",
    "Rate everyone's outfit out loud like a reality show judge.",
    "Narrate the next 30 seconds of your life like a nature documentary.",
    "Act out your last text conversation. Both sides. Full drama.",
    "Freestyle a 20-second rap about the person on your left.",
    "Deliver a villain monologue about why you're always late.",
    "Talk like an influencer doing a “get ready with me” for 30 seconds.",
    "Breakdance for 15 seconds. Falling counts.",
    "Interpretive dance your current relationship status.",
    "Lip sync a chorus the group picks. No shame allowed.",
    "Give a 20-second Oscar speech for winning “Most Chaotic.”",
    "Impersonate someone here until the group guesses who.",
    "Make a slow-motion entrance like the main character.",
    "Announce your own nickname like a stadium announcer.",
    "Speak only in questions until the next round.",
    "Use a British accent until the next round starts.",
    "Do 10 pushups while sharing your most useless talent.",
    "Sing “Happy Birthday” to the person on your right as a ballad.",
    "Do your best impression of an angry chef judging the snack table.",
    "Hype up the next person who speaks like they just won a championship.",
    "Give a dramatic weather report about the vibe in this room.",
    "Pitch a terrible startup idea like investors are watching.",
    "Do a dramatic slow clap every time someone says your name this round.",
    "Recreate the most embarrassing dance move you know.",
    "Act like a nervous contestant on a dating show for 30 seconds.",
  ],
  phone: [
    "Let the group scroll your camera roll for 10 seconds. No deleting.",
    "Post a story with a caption the group writes. Delete it after 10 minutes.",
    "Send a text the group writes to someone in your contacts. Keep it fun, not mean.",
    "Read your last Google search out loud.",
    "Show the group your screen time. No excuses.",
    "Let the group pick your profile pic for the next hour.",
    "Read the most recent thing in your notes app out loud.",
    "Show the group your most embarrassing saved photo and tell the story.",
    "Type “I think I'm” and read what autocomplete finishes. Three times, no editing.",
    "Show the last five apps you opened.",
    "Make your lock screen a selfie of someone in this room until tomorrow.",
    "Send a dramatic voice memo to the group chat about what you ate today.",
    "Record a 10-second video of your most dramatic reaction and send it to the group chat.",
    "Reply to your oldest unread message right now, in front of everyone.",
    "Play your most-listened song of the year and defend it.",
    "Show the group your most recent Google Maps search.",
    "Pick a contact and voice-note them a genuine compliment. Group listens.",
    "Let someone pick a filter. Take a selfie with it and post it to your story.",
    "Show everyone the last meme you sent and explain why it's funny.",
    "Read out the funniest message in your phone right now. Names stay hidden.",
    "Let the group write your next story caption. No edits.",
    "Open your emoji keyboard's recents and explain the top five.",
  ],
  spill: [
    "Tell the group your most embarrassing party moment.",
    "Give your honest hot take on the last person you dated. Keep it fair.",
    "Share your most irrational fear and defend it for 15 seconds.",
    "Name your biggest ick. Everyone else says if they have it too.",
    "Reveal one red flag you have. The group rates it 1 to 10.",
    "Tell the worst lie you've ever told.",
    "Share the pettiest reason you've ever stopped talking to someone.",
    "Say one thing you secretly love about everyone in the room.",
    "Confess a guilty-pleasure song. Everyone sings along.",
    "Name who you'd call first in an emergency, and who you'd never call.",
    "Tell your worst date story in 60 seconds.",
    "Admit one thing you've pretended to like to impress someone.",
    "Give everyone in the room a one-word nickname. No repeats.",
    "Rate everyone's rizz from 1 to 10. Be honest, be nice.",
    "Tell the room your most unpopular opinion and defend it.",
    "Spill the most embarrassing thing you've ever done for a crush.",
    "Name a celebrity crush and defend the choice in one dramatic sentence.",
    "Share the worst advice you've ever given.",
    "Tell your most chaotic childhood memory.",
    "Tell the group what you're most delulu about.",
    "Share what your friends would say your biggest flaw is.",
    "Describe your ideal Saturday night in 20 seconds. Zero dull details.",
    "Share the last thing that made you laugh so hard you cried.",
    "Tell us your most “I thought nobody saw that” moment.",
    "Share a secret talent nobody here knows about.",
  ],
  spicy: [
    "Give your best pickup line to the person on your left. Fully in character.",
    "Hold eye contact with someone who's down for 15 seconds. No laughing.",
    "Do your best baddie strut across the room and back.",
    "Run a 15-second compliment battle with someone: no repeats, no stopping.",
    "Do your impression of someone flirting badly.",
    "Wink at everyone in the room, one at a time, in slow motion.",
    "Serenade someone with the first line of any love song.",
    "Rate everyone's smile from 1 to 10.",
    "Deliver the most dramatic romantic line you can think of to the person across from you.",
    "Teach the room your best rizz move in 20 seconds.",
    "Whisper the back of a cereal box like it's a love poem.",
    "Pick two people and write their first-date plan in 20 seconds.",
    "Give your top three turn-ons and top three icks. PG-13 only.",
    "Rate your own rizz from 1 to 10. The room shouts the real number.",
    "Pitch someone here on a first date: where you'd go, why they'd say yes.",
    "Slow dance with a chair for 20 seconds. Make it romantic.",
    "Deliver a breakup speech to your phone. Make it dramatic.",
    "Whisper only until the next round.",
    "Tell someone here what makes them unfairly attractive, in one sentence.",
    "Reenact “love at first sight” with an object in the room.",
    "Act out your ideal meet-cute with someone of your choice.",
    "Give a convincing “I'm not like other people” speech while winking.",
    "Pick a fake plus-one and introduce them to the room with a full backstory.",
    "Read the snack labels in your sultriest voice.",
  ],
};

const DARE_LABELS = {
  show: "Show out",
  phone: "Phone out",
  spill: "Spill it",
  spicy: "Low-key spicy",
  custom: "From the room",
};

module.exports = { DEFAULT_QUESTIONS, DEFAULT_HINT, DEFAULT_DARES, DARE_LABELS };
